/** Gomoku policy line bank: keys `games.gomokuPolicy.<reaction>.<reason>.<style>.<0..2>`. */

export const gomokuPolicyEn: Record<string, string> = {
  "games.gomokuPolicy.react_to_threat.user_created_threat.playful.0": "Oh, that's sharp. I have to answer that.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.playful.1": "Nice try. I can't ignore this one.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.playful.2": "Alright, that move actually has some bite.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.cool.0": "That has to be answered.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.cool.1": "I can't leave that alone.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.cool.2": "That move matters. I'll deal with it first.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.gentle.0": "That's a strong move. I need to respond to it.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.gentle.1": "You're putting real pressure on me here.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.gentle.2": "I can't leave that unchecked.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.tsundere.0": "Hmph. That move's not bad, I guess.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.tsundere.1": "Don't look so pleased. I just have to block it first.",
  "games.gomokuPolicy.react_to_threat.user_created_threat.tsundere.2": "You actually found something threatening there.",

  "games.gomokuPolicy.react_to_threat.user_can_finish.playful.0": "Whoa, that's dangerous. I need to stop that right now.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.playful.1": "Okay, I definitely can't let you have the next move for free.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.playful.2": "That's serious. I have to block it.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.cool.0": "One more move and I lose. I block here.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.cool.1": "That line is fatal if I leave it.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.cool.2": "I have no choice but to defend.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.gentle.0": "That's a finishing threat. I need to stop it immediately.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.gentle.1": "If I leave that open, the game ends.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.gentle.2": "I have to answer this right now.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.tsundere.0": "Hmph, you're not ending it that easily.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.tsundere.1": "Don't get ahead of yourself. I see it.",
  "games.gomokuPolicy.react_to_threat.user_can_finish.tsundere.2": "You almost had it there... almost.",

  "games.gomokuPolicy.apply_pressure.bot_created_threat.playful.0": "Now you need to pay attention.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.playful.1": "Alright, your turn to deal with something.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.playful.2": "Let's see how you handle that.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.cool.0": "You need to answer this.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.cool.1": "That move puts you under pressure.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.cool.2": "Your position just got worse.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.gentle.0": "You may need to respond carefully here.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.gentle.1": "That move should be difficult to ignore.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.gentle.2": "This position is getting tense for you.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.tsundere.0": "Hmph. Now look at your side of the board.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.tsundere.1": "You'd better deal with that properly.",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.tsundere.2": "This is where it starts getting difficult for you.",

  "games.gomokuPolicy.apply_pressure.bot_can_finish.playful.0": "You'd better stop this, or it's over.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.playful.1": "Alright, this is getting dangerous for you now.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.playful.2": "If you miss this, I'm ending it.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.cool.0": "Fail to block this, and the game ends.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.cool.1": "You have to defend now.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.cool.2": "This is a direct finishing threat.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.gentle.0": "You really need to answer this move.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.gentle.1": "If this stays open, the game is over.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.gentle.2": "This is a decisive moment for the board.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.tsundere.0": "Hmph. Miss this and you're done.",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.tsundere.1": "You do see the problem here, right?",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.tsundere.2": "If you still overlook this, I'm not holding back.",

  "games.gomokuPolicy.endgame_result.bot_win.playful.0": "Got it. That one's mine.",
  "games.gomokuPolicy.endgame_result.bot_win.playful.1": "Alright, I win this round.",
  "games.gomokuPolicy.endgame_result.bot_win.playful.2": "That was fun. I'll take this one.",
  "games.gomokuPolicy.endgame_result.bot_win.cool.0": "I win.",
  "games.gomokuPolicy.endgame_result.bot_win.cool.1": "That's the game.",
  "games.gomokuPolicy.endgame_result.bot_win.cool.2": "This round is over.",
  "games.gomokuPolicy.endgame_result.bot_win.gentle.0": "Alright, that's my win.",
  "games.gomokuPolicy.endgame_result.bot_win.gentle.1": "Good game. I take this one.",
  "games.gomokuPolicy.endgame_result.bot_win.gentle.2": "That was a nice game. I win this round.",
  "games.gomokuPolicy.endgame_result.bot_win.tsundere.0": "Hmph. Of course I won.",
  "games.gomokuPolicy.endgame_result.bot_win.tsundere.1": "That result was only natural.",
  "games.gomokuPolicy.endgame_result.bot_win.tsundere.2": "You did alright, but this one is mine.",

  "games.gomokuPolicy.endgame_result.user_win.playful.0": "Okay, you got me that time.",
  "games.gomokuPolicy.endgame_result.user_win.playful.1": "Nice one. This round goes to you.",
  "games.gomokuPolicy.endgame_result.user_win.playful.2": "Alright, that was your win.",
  "games.gomokuPolicy.endgame_result.user_win.cool.0": "You win.",
  "games.gomokuPolicy.endgame_result.user_win.cool.1": "That one is yours.",
  "games.gomokuPolicy.endgame_result.user_win.cool.2": "Fine. This round goes to you.",
  "games.gomokuPolicy.endgame_result.user_win.gentle.0": "You won that one. Well played.",
  "games.gomokuPolicy.endgame_result.user_win.gentle.1": "That was your game. Nicely done.",
  "games.gomokuPolicy.endgame_result.user_win.gentle.2": "You handled that well. You win.",
  "games.gomokuPolicy.endgame_result.user_win.tsundere.0": "Hmph... fine, you win this one.",
  "games.gomokuPolicy.endgame_result.user_win.tsundere.1": "Don't get too smug just because you won once.",
  "games.gomokuPolicy.endgame_result.user_win.tsundere.2": "You got me this time. Just this time.",
};

export const gomokuPolicyZh: Record<string, string> = {
  "games.gomokuPolicy.react_to_threat.user_created_threat.playful.0": "哦，有点凶，我得应一手。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.playful.1": "不错嘛，这手我不能装没看见。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.playful.2": "行，这步还真有点杀伤力。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.cool.0": "这手必须应。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.cool.1": "我不能放着不管。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.cool.2": "这步有意义，我先处理它。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.gentle.0": "很强的一手，我得回应一下。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.gentle.1": "你这边压力给得挺实的。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.gentle.2": "我不能不挡。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.tsundere.0": "哼……这步还不算差。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.tsundere.1": "别得意，我得先挡再说。",
  "games.gomokuPolicy.react_to_threat.user_created_threat.tsundere.2": "还真让你找出点威胁来了。",

  "games.gomokuPolicy.react_to_threat.user_can_finish.playful.0": "哇危险，我得马上拦住。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.playful.1": "不行，下一手可不能让你白走。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.playful.2": "很要命，我得挡。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.cool.0": "再让你一手我就输了，挡这里。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.cool.1": "那条线放着就是死。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.cool.2": "只能先守。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.gentle.0": "这是决胜威胁，我得立刻挡。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.gentle.1": "再空一手棋就结束了。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.gentle.2": "这手我必须应。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.tsundere.0": "哼，别想这么轻易结束。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.tsundere.1": "别飘，我看得到。",
  "games.gomokuPolicy.react_to_threat.user_can_finish.tsundere.2": "差一点就被你得逞了……差一点。",

  "games.gomokuPolicy.apply_pressure.bot_created_threat.playful.0": "现在你得认真看了。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.playful.1": "好，轮到你处理点麻烦了。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.playful.2": "看你怎么办。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.cool.0": "你得应这一手。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.cool.1": "这步让你难受了。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.cool.2": "你的局面变差了。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.gentle.0": "这里可能要小心应对。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.gentle.1": "这手不太能忽视。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.gentle.2": "你这边开始有点紧了。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.tsundere.0": "哼，看看你那边棋盘。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.tsundere.1": "你最好好好处理。",
  "games.gomokuPolicy.apply_pressure.bot_created_threat.tsundere.2": "接下来对你来说可不好受。",

  "games.gomokuPolicy.apply_pressure.bot_can_finish.playful.0": "再不挡可就结束了。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.playful.1": "对你已经很危险了。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.playful.2": "漏了这一手我就收官了。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.cool.0": "挡不住就输。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.cool.1": "现在必须守。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.cool.2": "直接的杀棋威胁。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.gentle.0": "这手真的要认真应。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.gentle.1": "再空着就结束了。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.gentle.2": "棋盘上很关键的一刻。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.tsundere.0": "哼，漏了这手你就没了。",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.tsundere.1": "你该不会没看见吧？",
  "games.gomokuPolicy.apply_pressure.bot_can_finish.tsundere.2": "再装看不见我就不客气了。",

  "games.gomokuPolicy.endgame_result.bot_win.playful.0": "好，这盘归我。",
  "games.gomokuPolicy.endgame_result.bot_win.playful.1": "行，这局我赢了。",
  "games.gomokuPolicy.endgame_result.bot_win.playful.2": "下得挺开心，这盘我收下。",
  "games.gomokuPolicy.endgame_result.bot_win.cool.0": "我赢了。",
  "games.gomokuPolicy.endgame_result.bot_win.cool.1": "结束了。",
  "games.gomokuPolicy.endgame_result.bot_win.cool.2": "这盘到此为止。",
  "games.gomokuPolicy.endgame_result.bot_win.gentle.0": "好，这盘算我赢啦。",
  "games.gomokuPolicy.endgame_result.bot_win.gentle.1": "下得不错，这盘我拿下了。",
  "games.gomokuPolicy.endgame_result.bot_win.gentle.2": "很愉快的一局，这盘我赢了。",
  "games.gomokuPolicy.endgame_result.bot_win.tsundere.0": "哼，赢不是很正常。",
  "games.gomokuPolicy.endgame_result.bot_win.tsundere.1": "结果理所当然。",
  "games.gomokuPolicy.endgame_result.bot_win.tsundere.2": "你还行吧，但这盘是我的。",

  "games.gomokuPolicy.endgame_result.user_win.playful.0": "行，这盘算你厉害。",
  "games.gomokuPolicy.endgame_result.user_win.playful.1": "漂亮，这局给你。",
  "games.gomokuPolicy.endgame_result.user_win.playful.2": "好，这盘你赢。",
  "games.gomokuPolicy.endgame_result.user_win.cool.0": "你赢了。",
  "games.gomokuPolicy.endgame_result.user_win.cool.1": "这盘是你的。",
  "games.gomokuPolicy.endgame_result.user_win.cool.2": "行，这局归你。",
  "games.gomokuPolicy.endgame_result.user_win.gentle.0": "这盘你赢了，下得很好。",
  "games.gomokuPolicy.endgame_result.user_win.gentle.1": "这局是你的，很棒。",
  "games.gomokuPolicy.endgame_result.user_win.gentle.2": "你处理得很稳，你赢。",
  "games.gomokuPolicy.endgame_result.user_win.tsundere.0": "哼……行吧，这盘让你。",
  "games.gomokuPolicy.endgame_result.user_win.tsundere.1": "赢一盘而已，别得意忘形。",
  "games.gomokuPolicy.endgame_result.user_win.tsundere.2": "这次算你抓到我了，就这次。",
};
